name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # Explicit permission to create releases

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for full tag history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: List build output
        run: dir dist

      - name: Salvar certificado de assinatura
        run: |
          [System.Convert]::FromBase64String("${{ secrets.CODESIGN_PFX }}") | Set-Content -Path codesign.pfx -AsByteStream
        shell: pwsh

      - name: Assinar o executável
        run: |
          "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\signtool.exe" sign /f codesign.pfx /p "${{ secrets.CODESIGN_PFX_PASSWORD }}" /tr http://timestamp.digicert.com /td sha256 /fd sha256 ./dist/AutoWabba.exe

      - name: Verificar certificado decodificado
        run: |
          head -c 32 codesign.pfx | hexdump -C

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/AutoWabba.exe
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
